// technical data fetch
export const TECHNICALEVENT_DATA_REQUEST = 'TECHNICAL_DATA_REQUEST'
export const TECHNICALEVENT_DATA_SUCCESS = 'TECHNICAL_DATA_SUCCESS'
export const TECHNICALEVENT_DATA_FAILURE = 'TECHNICAL_DATA_FAILURE'

//nontechnical data fetch
export const NONTECHNICALEVENT_DATA_REQUEST = 'NONTECHNICAL_DATA_REQUEST'
export const NONTECHNICALEVENT_DATA_SUCCESS = 'NONTECHNICAL_DATA_SUCCESS'
export const NONTECHNICALEVENT_DATA_FAILURE = 'NONTECHNICAL_DATA_FAILURE'

//GetIndividualEvent data fetch
export const GETINDIVIDUALEVENT_DATA_REQUEST = 'GETINDIVIDUALEVENT_DATA_REQUEST'
export const GETINDIVIDUALEVENT_DATA_SUCCESS = 'GETINDIVIDUALEVENT_DATA_SUCCESS'
export const GETINDIVIDUALEVENT_DATA_FAILURE = 'GETINDIVIDUALEVENT_DATA_FAILURE'

//Courses data fetched
export const COURSES_DATA_REQUEST = 'COURSES_DATA_REQUEST'
export const COURSES_DATA_SUCCESS = 'COURSES_DATA_SUCCESS'
export const COURSES_DATA_FAILURE = 'COURSES_DATA_FAILURE'

//login id and username
export const GETUSERID = 'GETUSERID'
export const GETUSERNAME = 'GETUSERNAME'
export const GETADMINID="GETADMINID"
export const GETADMINNAME="GETADMINNAME"

//addEventTOUser Data
export const GET_USER_TECH_DATA_REQUEST = 'GET_USER_TECH_DATA_REQUEST'
export const GET_USER_TECH_DATA_SUCCESS = 'GET_USER_TECH_DATA_SUCCESS'
export const GET_USER_TECH_DATA_FAILURE = 'GET_USER_TECH_DATA_FAILURE'


export const GET_ALL_USER_DATA_REQUEST="GET_ALL_USER_DATA_REQUEST"
export const GET_ALL_USER_DATA_SUCCESS="GET_ALL_USER_DATA_SUCCESS"
export const GET_ALL_USER_DATA_FAILURE="GET_ALL_USER_DATA_FAILURE"
