
// technical data fetch
export const TECHNICALEVENT_DATA_REQUEST="TECHNICAL_DATA_REQUEST"
export const TECHNICALEVENT_DATA_SUCCESS="TECHNICAL_DATA_SUCCESS"
export const TECHNICALEVENT_DATA_FAILURE="TECHNICAL_DATA_FAILURE"


//nontechnical data fetch
export const NONTECHNICALEVENT_DATA_REQUEST="NONTECHNICAL_DATA_REQUEST"
export const NONTECHNICALEVENT_DATA_SUCCESS="NONTECHNICAL_DATA_SUCCESS"
export const NONTECHNICALEVENT_DATA_FAILURE="NONTECHNICAL_DATA_FAILURE"